from __future__ import annotations

import json
from pathlib import Path
from typing import Any

_RUNNER_MAP = {
    "windows": "windows-latest",
    "linux": "ubuntu-latest",
    "macos": "macos-latest",
    "darwin": "macos-latest",
    "ubuntu": "ubuntu-latest",
    "win": "windows-latest",
    "mac": "macos-latest",
}

_WORKFLOW_TEMPLATE = """\
# Generated by OtterForge CI Generator — do not edit manually.
name: OtterForge Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
{jobs}
"""

_JOB_TEMPLATE = """\
  {job_id}:
    runs-on: {runner}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install OtterForge
        run: pip install otterforge
      - name: Build
        run: otterforge build --builder {builder} --project-path .
      - name: Package
        run: otterforge package --project-path .
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-{job_id}
          path: dist/
"""


class CIGenerator:
    """Generate CI pipeline configuration files for OtterForge projects."""

    # --------------------------------------------------------------------- #
    # GitHub Actions                                                          #
    # --------------------------------------------------------------------- #

    def generate_github_actions(
        self,
        project_path: str | Path,
        profiles: list[dict[str, Any]],
        output_path: str | Path | None = None,
    ) -> dict[str, Any]:
        jobs_yaml = ""
        for entry in profiles:
            platform = str(entry.get("platform", "linux")).lower()
            runner = _RUNNER_MAP.get(platform, "ubuntu-latest")
            builder = str(entry.get("builder_name", "auto"))
            label = str(entry.get("profile_name", f"{platform}_{builder}"))
            job_id = label.lower().replace(" ", "_").replace("-", "_")

            jobs_yaml += _JOB_TEMPLATE.format(
                job_id=job_id,
                runner=runner,
                builder=builder,
            )

        workflow = _WORKFLOW_TEMPLATE.format(jobs=jobs_yaml)

        saved_to: str | None = None
        if output_path is not None:
            out = Path(output_path)
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(workflow, encoding="utf-8")
            saved_to = str(out.resolve())
        else:
            out = Path(project_path) / ".github" / "workflows" / "otterforge.yml"
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(workflow, encoding="utf-8")
            saved_to = str(out.resolve())

        return {
            "provider": "github",
            "saved_to": saved_to,
            "jobs": len(profiles),
            "workflow": workflow,
        }

    # --------------------------------------------------------------------- #
    # Profile export                                                          #
    # --------------------------------------------------------------------- #

    def export_profile(
        self,
        profile_name: str,
        profile_data: dict[str, Any],
        output_path: str | Path | None = None,
    ) -> dict[str, Any]:
        payload = {
            "profile_name": profile_name,
            **profile_data,
        }
        saved_to: str | None = None
        if output_path is not None:
            out = Path(output_path)
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(json.dumps(payload, indent=2), encoding="utf-8")
            saved_to = str(out.resolve())

        return {"profile_name": profile_name, "saved_to": saved_to, "data": payload}
