#!/usr/bin/env python3
"""
FinancialManager - PyQt6 GUI Application
Generated by PyInstaller Build Tool
"""

import sys
from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget, QVBoxLayout, QLabel, QPushButton, QMessageBox

class FinancialmanagerWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("FinancialManager")
        self.setGeometry(100, 100, 800, 600)
        
        self.setup_ui()
    
    def setup_ui(self):
        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        
        layout = QVBoxLayout()
        central_widget.setLayout(layout)
        
        # Welcome label
        welcome_label = QLabel("Welcome to FinancialManager!")
        welcome_label.setStyleSheet("font-size: 18px; font-weight: bold; margin: 20px;")
        layout.addWidget(welcome_label)
        
        # Sample button
        button = QPushButton("Click Me!")
        button.clicked.connect(self.on_button_click)
        layout.addWidget(button)
    
    def on_button_click(self):
        QMessageBox.information(self, "Hello", "Hello from FinancialManager!")

def main():
    app = QApplication(sys.argv)
    window = FinancialmanagerWindow()
    window.show()
    sys.exit(app.exec())

if __name__ == "__main__":
    main()
